package com.shuoyi.model.user;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Continent
     *
     * @mbg.generated
     */
    private String continent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.SurfaceArea
     *
     * @mbg.generated
     */
    private Float surfacearea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.IndepYear
     *
     * @mbg.generated
     */
    private Short indepyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Population
     *
     * @mbg.generated
     */
    private Integer population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LifeExpectancy
     *
     * @mbg.generated
     */
    private Float lifeexpectancy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNP
     *
     * @mbg.generated
     */
    private Float gnp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNPOld
     *
     * @mbg.generated
     */
    private Float gnpold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LocalName
     *
     * @mbg.generated
     */
    private String localname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GovernmentForm
     *
     * @mbg.generated
     */
    private String governmentform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.HeadOfState
     *
     * @mbg.generated
     */
    private String headofstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Capital
     *
     * @mbg.generated
     */
    private Integer capital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code2
     *
     * @mbg.generated
     */
    private String code2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code
     *
     * @return the value of country.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code
     *
     * @param code the value for country.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Name
     *
     * @return the value of country.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Name
     *
     * @param name the value for country.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Continent
     *
     * @return the value of country.Continent
     *
     * @mbg.generated
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Continent
     *
     * @param continent the value for country.Continent
     *
     * @mbg.generated
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Region
     *
     * @return the value of country.Region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Region
     *
     * @param region the value for country.Region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.SurfaceArea
     *
     * @return the value of country.SurfaceArea
     *
     * @mbg.generated
     */
    public Float getSurfacearea() {
        return surfacearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.SurfaceArea
     *
     * @param surfacearea the value for country.SurfaceArea
     *
     * @mbg.generated
     */
    public void setSurfacearea(Float surfacearea) {
        this.surfacearea = surfacearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.IndepYear
     *
     * @return the value of country.IndepYear
     *
     * @mbg.generated
     */
    public Short getIndepyear() {
        return indepyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.IndepYear
     *
     * @param indepyear the value for country.IndepYear
     *
     * @mbg.generated
     */
    public void setIndepyear(Short indepyear) {
        this.indepyear = indepyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Population
     *
     * @return the value of country.Population
     *
     * @mbg.generated
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Population
     *
     * @param population the value for country.Population
     *
     * @mbg.generated
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LifeExpectancy
     *
     * @return the value of country.LifeExpectancy
     *
     * @mbg.generated
     */
    public Float getLifeexpectancy() {
        return lifeexpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LifeExpectancy
     *
     * @param lifeexpectancy the value for country.LifeExpectancy
     *
     * @mbg.generated
     */
    public void setLifeexpectancy(Float lifeexpectancy) {
        this.lifeexpectancy = lifeexpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNP
     *
     * @return the value of country.GNP
     *
     * @mbg.generated
     */
    public Float getGnp() {
        return gnp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNP
     *
     * @param gnp the value for country.GNP
     *
     * @mbg.generated
     */
    public void setGnp(Float gnp) {
        this.gnp = gnp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNPOld
     *
     * @return the value of country.GNPOld
     *
     * @mbg.generated
     */
    public Float getGnpold() {
        return gnpold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNPOld
     *
     * @param gnpold the value for country.GNPOld
     *
     * @mbg.generated
     */
    public void setGnpold(Float gnpold) {
        this.gnpold = gnpold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LocalName
     *
     * @return the value of country.LocalName
     *
     * @mbg.generated
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LocalName
     *
     * @param localname the value for country.LocalName
     *
     * @mbg.generated
     */
    public void setLocalname(String localname) {
        this.localname = localname == null ? null : localname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GovernmentForm
     *
     * @return the value of country.GovernmentForm
     *
     * @mbg.generated
     */
    public String getGovernmentform() {
        return governmentform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GovernmentForm
     *
     * @param governmentform the value for country.GovernmentForm
     *
     * @mbg.generated
     */
    public void setGovernmentform(String governmentform) {
        this.governmentform = governmentform == null ? null : governmentform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.HeadOfState
     *
     * @return the value of country.HeadOfState
     *
     * @mbg.generated
     */
    public String getHeadofstate() {
        return headofstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.HeadOfState
     *
     * @param headofstate the value for country.HeadOfState
     *
     * @mbg.generated
     */
    public void setHeadofstate(String headofstate) {
        this.headofstate = headofstate == null ? null : headofstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Capital
     *
     * @return the value of country.Capital
     *
     * @mbg.generated
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Capital
     *
     * @param capital the value for country.Capital
     *
     * @mbg.generated
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code2
     *
     * @return the value of country.Code2
     *
     * @mbg.generated
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code2
     *
     * @param code2 the value for country.Code2
     *
     * @mbg.generated
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Country other = (Country) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getContinent() == null ? other.getContinent() == null : this.getContinent().equals(other.getContinent()))
            && (this.getRegion() == null ? other.getRegion() == null : this.getRegion().equals(other.getRegion()))
            && (this.getSurfacearea() == null ? other.getSurfacearea() == null : this.getSurfacearea().equals(other.getSurfacearea()))
            && (this.getIndepyear() == null ? other.getIndepyear() == null : this.getIndepyear().equals(other.getIndepyear()))
            && (this.getPopulation() == null ? other.getPopulation() == null : this.getPopulation().equals(other.getPopulation()))
            && (this.getLifeexpectancy() == null ? other.getLifeexpectancy() == null : this.getLifeexpectancy().equals(other.getLifeexpectancy()))
            && (this.getGnp() == null ? other.getGnp() == null : this.getGnp().equals(other.getGnp()))
            && (this.getGnpold() == null ? other.getGnpold() == null : this.getGnpold().equals(other.getGnpold()))
            && (this.getLocalname() == null ? other.getLocalname() == null : this.getLocalname().equals(other.getLocalname()))
            && (this.getGovernmentform() == null ? other.getGovernmentform() == null : this.getGovernmentform().equals(other.getGovernmentform()))
            && (this.getHeadofstate() == null ? other.getHeadofstate() == null : this.getHeadofstate().equals(other.getHeadofstate()))
            && (this.getCapital() == null ? other.getCapital() == null : this.getCapital().equals(other.getCapital()))
            && (this.getCode2() == null ? other.getCode2() == null : this.getCode2().equals(other.getCode2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getContinent() == null) ? 0 : getContinent().hashCode());
        result = prime * result + ((getRegion() == null) ? 0 : getRegion().hashCode());
        result = prime * result + ((getSurfacearea() == null) ? 0 : getSurfacearea().hashCode());
        result = prime * result + ((getIndepyear() == null) ? 0 : getIndepyear().hashCode());
        result = prime * result + ((getPopulation() == null) ? 0 : getPopulation().hashCode());
        result = prime * result + ((getLifeexpectancy() == null) ? 0 : getLifeexpectancy().hashCode());
        result = prime * result + ((getGnp() == null) ? 0 : getGnp().hashCode());
        result = prime * result + ((getGnpold() == null) ? 0 : getGnpold().hashCode());
        result = prime * result + ((getLocalname() == null) ? 0 : getLocalname().hashCode());
        result = prime * result + ((getGovernmentform() == null) ? 0 : getGovernmentform().hashCode());
        result = prime * result + ((getHeadofstate() == null) ? 0 : getHeadofstate().hashCode());
        result = prime * result + ((getCapital() == null) ? 0 : getCapital().hashCode());
        result = prime * result + ((getCode2() == null) ? 0 : getCode2().hashCode());
        return result;
    }
}